#!/usr/bin/env bash
# this is a script to transfer files to a remote server
# the script takes all needed credentials from the cli

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1

else  
  file_path=$1
  ip=$2
  username=$3
  key=$4

  scp -i "$key" -r "$file_path" "$username"@"$ip":~
fi  
