#!/usr/bin/env bash
# script to install and display 'Hello world!' on a nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
