#!/usr/bin/env bash
# script to install and display 'Hello world!' on a nginx server

sudo apt -y update
sudo apt -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
