#!/usr/bin/env bash
# script to install and display 'Hello world!' on a nginx server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
