#!/usr/bin/env bash
#displays indefinitely
#traps different signals

delete_file()
{
	rm -f  /var/run/myscript.pid;
	exit
}

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'delete_file' SIGQUIT SIGTERM

echo $$ >> /var/run/myscript.pid

while true
do
   echo "To infinity and beyond"
   sleep 2
done    
