#!/usr/bin/env bash
#prints indefinitely and diplays 'I am invincible' when a SIGTERM signal is
#received

i=1
while [ $i -gt 0 ]
do
    echo "To infinity and beyond"
    trap 'echo "I am invincible!!!"' SIGTERM
    sleep 2
    ((i++))
done
