#!/usr/bin/env bash
#prints indefinitely and diplays 'I am invincible' when a SIGTERM signal is
#received
trap 'echo "I am invincible!!!"' SIGTERM


while true 
do
    echo "To infinity and beyond"
    sleep 2
done
